### ISSUE TITLE
Add bytes formatting

### ISSUE THREAD

**Issue by gustavohenke** [epeli/underscore.string#198]
Hey,
It would be nice to have a function to format byte sizes... for example:
- 1024 => 1 KB
- 1536 => 1.5 KB
- 1048576 => 1 MB

Also, maybe some argument to limit the maximum size...
```javascript
_s.byteFormat( 1048576, "KB" ); // Would be 1024 KB
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/pretty-bytes

**Comment by epeli** [comment]
http://filesizejs.com/

This is too domain specific.
