### ISSUE TITLE
Request: camelBack

### ISSUE THREAD

**Issue by srsgores** [epeli/underscore.string#228]
As useful as ``_camelize(string)`` is, I would like to be able to convert strings into [camel back notation](http://en.wikipedia.org/wiki/CamelCase) where the first letter of the string is always lower-case:

```
var myString = "stuff-to-be-converted";
var convertedString = _camelizeBack(myString);
```

Yielding:

```
"stuffToBeConverted"
```

**Comment by stoeffel** [comment]
Documentation for `camelize` is updated.

**Comment by srsgores** [comment]
So there are no plans for a ``camelizeBack`` method?

**Comment by stoeffel** [comment]
No, it is still `camelize` (alias `camelcase`) but you can pass a flag if you want it to always start with a lowercase letter.

```js
camelize('foo bar') // => fooBar
camelize('Foo bar') // => FooBar
camelize('Foo bar', true) // => fooBar
```

http://epeli.github.io/underscore.string/#camelize-string-decapitalize-false-gt-string

**Comment by srsgores** [comment]
Ah, thanks, @stoeffel

**Comment by stoeffel** [comment]
No problem :bowtie:
