### ISSUE TITLE
Underscore.String Can Only be Used With Require if its in the Root Folder

### ISSUE THREAD

**Issue by machineghost** [epeli/underscore.string#265]
Underscore.String adds AMD support with the following code:

    define('underscore.string', [], function() {
        return _s;
    });

The problem with that is that it says "define the path 'underscore.string' as being ...".  The thing is though, not everyone puts the library in the root path of their setup; I (and I imagine most others) put it in a subfolder, in my case "ext".

You can fix this by eliminating the first argument (it isn't necessary at all):

    define([], function() {
        return _s;
    });

If you do this Require will just define it based on the file's path, which will be "underscore.string" if the file is in the root path, but otherwise will be the appropriate path for the file (eg. 'ext/underscore.string').

Could you please consider eliminating this argument?

**Comment by lsapan** [comment]
+1, this just caused me tons of headache. At the very least, add it to the note on the webpage about RequireJS.

**Comment by epeli** [comment]
The AMD build is generated by Browserify's standalone feature which uses the  `umd` module on npm. Maybe this issue should be taken there?

https://github.com/ForbesLindesay/umd

**Comment by lsapan** [comment]
My apologies, I commented on this issue a moment ago before actually testing it was the fix. As it turns out, it no longer defines itself with an alias.

**Comment by epeli** [comment]
np
