### ISSUE TITLE
Surprised not to see certain methods

### ISSUE THREAD

**Issue by ronnieoverby** [epeli/underscore.string#280]
Hopefully I'm just missing something, but I'm surprised not to see these functions in this library:

 - remove specified characters from string
 - remove all but specified characters from string

**Comment by stoeffel** [comment]
Since 3.0 there is `replaceAll` and the native `replace`.
To remove specified characters from a string use:
```js
s('hello').replace('l','').value(); // => "helo"
```
To remove all but specified characters from a string use: 
```js
s('hello').replaceAll('l','').value(); // => "heo"
```
