### ISSUE TITLE
unescapeHTML does not work with &nbsp;

### ISSUE THREAD

**Issue by Broham** [epeli/underscore.string#301]
When I try to unescape ```&nbsp;``` it does not work. For example if I run this code:

```
console.log _s.unescapeHTML("&nbsp;")
```
it outputs ```&nbsp;```

Can this be done using underscore.string?

**Comment by srmelody** [comment]
@Broham @stoeffel does my PR meet the needs of the issue?

**Comment by stoeffel** [comment]
@srmelody I will check it out this WE. Thanks for your PR

**Comment by srmelody** [comment]
Great thanks @stoeffel :)
