### ISSUE TITLE
._camelize('Sample Text') returning "SampleText", not "sampleText"

### ISSUE THREAD

**Issue by joshuahiggins** [epeli/underscore.string#306]
The documentation is confusing, as it indicates the following (emphasis added):

> Converts underscored or dasherized string to a camelized one. **Begins with a lower case letter** unless it starts with an underscore or **string**

The example that follows shows a dash utilized to prompt a lowercase letter, which is neither an underscore nor a string. Should the documentation read as `underscore or dash`? It wouldn't make sense that it starts with a lower case letter unless it starts with a string.

Camelizing the phrase "Sample Text" should return "sampleText", not "SampleText".

**Comment by bolora** [comment]
We use this workaround using &lowbar;.underscored which works correctly.
_.dasherize(&lowbar;.underscored( 'FooBar' )) returns 'foo-bar'

**Comment by joshuahiggins** [comment]
Your solution does not resolve the issue as described. Also, this issue has already been closed as functionality has already been introduced.
