### ISSUE TITLE
add support in titleize: english capitalization rules

### ISSUE THREAD

**Issue by raitucarp** [epeli/underscore.string#317]
Could you add support for titleize such this one?

http://sugarjs.com/api/String/titleize

for reference:
http://english.stackexchange.com/questions/14/which-words-in-a-title-should-be-capitalized

update refererence:
http://ejohn.org/blog/title-capitalization-in-javascript/#postcomment

**Comment by stoeffel** [comment]
This does only work for english and would be weird for other languages, however the current implementation works for all languages.

i.e.
```js
// in english
titleize("foo_in_a_bar"); // => "Foo in a Bar" (as expected)

// in german
titleize("foo_in_einem_bar"); // => "Foo in Einem Bar" (it should be "Foo in einem Bar")
```

**Comment by stoeffel** [comment]
[CONTRIBUTING.markdown](https://github.com/epeli/underscore.string/blob/master/CONTRIBUTING.markdown#new-features)
> For example anything related to internalization or is too language specific is out of scope

IMHO this is to language specific.
