### ISSUE TITLE
Better LoDash support when wrapping

### ISSUE THREAD

**Issue by mwisnicki** [epeli/underscore.string#325]
At the moment if I integrate underscore.string into lodash with

```
_.mixin(_.str.exports());
```

All methods will chain by default. According to lodash intuitive chaining rules, methods that return primitive values should not chain.

This sets following expectations
```
expect( _("abc").startsWith("z") ).toBe(false);
expect( _("a\nc").lines().value() ).toEqual(["a", "b"]);
```

At the moment first assertion is broken.

Chaining can be disabled by passing `{ 'chain': false }` as a second argument to mixin.

underscore.string should provide a way to determine whether method should be chained and a helper function to install itself.

In the mean time, documentation should mention this gotcha when using lodash instead of underscore and perhaps suggest

```
_.mixin(_.string.exports() , { 'chain': false });
```

**Comment by anthonator** [comment]
:+1: for updating the documentation before 3.0

**Comment by stoeffel** [comment]
3.0 is here :smile:
