### ISSUE TITLE
Decapitalize is not available

### ISSUE THREAD

**Issue by enzolutions** [epeli/underscore.string#375]
I'm working in a nodejs project and I add underscore string in my package.json file with following instructions.

```
  "dependencies": {
    "request": "~2.21.0",
    "async": "~0.2.8",
    "inquirer": "^0.8.0",
    "underscore": "~1.4.4",
    "underscore.string": "~2.4.0",
    "sync-request": "~1.0.1"
  },
```

The installation works without any problems, but when I try to use the function decapitalize like this

```
var _s = require('underscore.string');
var name = _s.underscored(_s.decapitalize(this.Model));
```

I got the following error.

```
TypeError: Object #<Object> has no method 'decapitalize'
```

Looks like the version for npm doesn't contain that function

**Comment by stoeffel** [comment]
Version 3.0.0 is not published yet. You have to wait for a little longer.

**Comment by stoeffel** [comment]
In the meantime you can create your own function.
```js
function decapitalize(str) {
    return str && str[0].toLowerCase() + str.slice(1);
}
```

**Comment by TheunisKotze** [comment]
Why not include this in a minor release? Otherwise, docs should be updated to indicate it's not available in release yet

**Comment by stoeffel** [comment]
Yes I think we have to create a develop branch for future work (like i.e. moment.js). Master is currently our WIP-Branch and this leads to confusing documentation. Or maybe we could just create an online documentation.

**Comment by epeli** [comment]
Online docs +1.

I think the master branch should always be the one we want to get PRs for.

**Comment by stoeffel** [comment]
I will start working on this next week.

Esa-Matti Suuronen <notifications@github.com> schrieb am Mon Jan 05 2015 at
11:10:04 AM:

**Comment by epeli** [comment]
Should be easy enough as rendering the readme markdown to a html file on releases.
