### ISSUE TITLE
[feature request] Replace a character at a particular index

### ISSUE THREAD

**Issue by rain1024** [epeli/underscore.string#377]
underscore.string is great. Love to use it.

I hope a function `set` appear in `underscore.string`

```js
var s = "abc"
_.string.set(s, 2, "d")
=> abd
```

Like this http://stackoverflow.com/questions/1431094/how-do-i-replace-a-character-at-a-particular-index-in-javascript

**Comment by epeli** [comment]
Use splice? 

```js
splice(s, 2, 1, "d")
```

https://github.com/epeli/underscore.string#splicestring-index-howmany-substring--string

**Comment by rain1024** [comment]
(y) thank you epeli
