### ISSUE TITLE
What is the global name of this library?

### ISSUE THREAD

**Issue by hekevintran** [epeli/underscore.string#381]
The readme says that the global is named `s`, but when I load this file, `s` is undefined and I must use _.string.

**Comment by stoeffel** [comment]
You have to use `_.string` or `_.str` there is no global named `s`.
Checkout the documentation of the current release: https://github.com/epeli/underscore.string/blob/2.4.0/README.markdown

**Comment by epeli** [comment]
Actually there is starting of 3.0.

https://github.com/epeli/underscore.string/blob/master/gulpfile.js#L25

**Comment by stoeffel** [comment]
Whoops forgot the "yet"

> You have to use _.string or _.str there is no global named s ***yet***.

:smile:

**Comment by hekevintran** [comment]
The 2.4.0 readme says:

As name states this an extension for Underscore.js (and Lo-Dash), but it can be used independently from _s-global variable. But with Underscore.js you can use Object-Oriented style and chaining:

The current master readme says:

The dist/underscore.string.js file is an UMD build. You can load it using an AMD loader such as RequireJS or just stick it to a web page and access the library from the s global.

My problem with this is 2 things:

1) They are both incorrect and misleading.  In version 2.4.0 readme it says there is a `_s` value, but there is no `_s` value.  In the master branch which I assume will become 3.0 the readme says there is a `s` value, but there is no `s` value.  The current master branch's bower.json says that the version is 2.4.0.   This is extremely confusing and wastes time for new users because the readmes are literally lying.

2) The current master readme says to use a value that doesn't exist and does not list the values that do exist at all.  There is no mention in the readme that you should call your functions from the `_.string` namespace.  There's just a list of functions descriptions will no example code at all.

**Comment by stoeffel** [comment]
> 1) In version 2.4.0 readme it says there is a _s value, but there is no _s value.

Yes that's true, `_s` doesn't exist. Sorry for that. You have to use `_.str`

> 2) The current master readme says to use a value that doesn't exist

The global `s` will exist as soon as 3.0 is released. 
As stated in the readme:
> This documentation for the development version.

The readme of the master is the readme for the version currently under development.
We hope we can reduce this confusion as soon as the new project page is released.
