### ISSUE TITLE
Can't load underscore.string v3 using RequireJS

### ISSUE THREAD

**Issue by lsapan** [epeli/underscore.string#397]
I've tried a wide variety of methods, but I simply cannot use underscore.string when loaded through AMD. The result of loading it through RequireJS is always `undefined`, and it isn't attaching itself to the window object as `s` either.

I've tried adding a shim but that doesn't fix it either (not that I figured it would).

Edit: For the record, v2 works beautifully in the same setup. I simply replaced the file with v3.

**Comment by stoeffel** [comment]
Hmmm... It works for me [jsbin](http://jsbin.com/wusuligabi/3/edit)

**Comment by lsapan** [comment]
Err.. it works through the CDN. Huh. I guess there's something mysterious going on locally, thanks!

**Comment by stoeffel** [comment]
No problem. 
Did you point requirejs to `dist/underscore.string.js` or to `index.js`?
For requirejs you should use `dist/underscore.string.js` or `dist/underscore.string.min.js`.

**Comment by lsapan** [comment]
As it turns out, I downloaded the latest build and it is working now. I had downloaded it a few days ago, not sure if something was fixed between then. I'm 99% sure I had downloaded the dist version, but who knows. It works now, thanks!

**Comment by stoeffel** [comment]
:smile:

**Comment by sandboxws** [comment]
I'm facing the same problem with the latest version 3.1.1, it's not working with requirejs, below is my main.coffee file

```coffeescript
requirejs.config
  baseUrl: '/js'
  shim:
    'jquery':
      exports: '$'

    'underscore':
      exports: '_'

    'underscore.string':
      deps: ['underscore']

  paths:
    'underscore': './../../../../public/assets/vendor/underscore/underscore'
    'underscore.string': './../../../../public/assets/vendor/underscore.string/dist/underscore.string'
    'jquery': './../../../../public/assets/vendor/jquery/dist/jquery.min'
```

and this is my bower.json file

```json
{
  "devDependencies": {
    "jquery": "~2.1.4",
    "bootstrap": "~3.3.5",
    "font-awesome": "~4.3.0",
    "moment": "~2.10.3",
    "underscore": "~1.8.3",
    "underscore.string": "~3.1.1",
    "requirejs": "*"
  }
}
```
