### ISSUE TITLE
Add regex support for replaceAll

### ISSUE THREAD

**Issue by anthonator** [epeli/underscore.string#398]
Being able to do a ```gsub``` type replace with regex would be great.

```js
_.replaceAll(phoneNumber, /[^\d]+/, ''); // (555) 555-5555 -> 5555555555
```

**Comment by epeli** [comment]
Javascript Regexp supports this directly. Just append `g` to your regexp and it does exactly that

    (555) 555-5555".replace(/[^\d]+/g, "") === "5555555555"
