### ISSUE TITLE
Unable to add library to repo because the `/dist` directory is ignored

### ISSUE THREAD

**Issue by caspyin** [epeli/underscore.string#400]
Problem
=======

I'm using this project in a Rails app that I've wired up to use Bower to manage dependencies and am deploying to Heroku. 

I have a staging environment and everything would work fine when I ran the app in staging locally but when I pushed to Heroku, I would get an error about Sprockets not being able to find the file `underscore.string/dist/underscore.string.js`. When I looked on the Heroku file system, sure enough the `/dist` directory wasn't there.

Eventually I realized the reason this was happening is because I was adding all of my `bower_components` to the repo so Heroku would just use what was being pushed rather than downloading fresh from a `bower install`. Now because the `/dist` directory is in the `.gitignore` file for this project it wasn't being added to the `bower_components/underscore.string/` folder in my repo and therefore never pushed to Heroku.

I solved my problem by removing this library from the `bower_components` folder in the repo and just let Heroku download it. However this isn't ideal because I would like to have the option to store the library in my repo if I want.

So as I understand it, since the `/dist` directory is ignored in this project no one is able to simply do a `bower install --save` and commit this lib to their repo. If you want this lib stored in your repo you have to either:

* Force commit the `/dist` folder to the repo
* Don't add to the repo and instead have the server download the library.

Solutions
=======

I've never maintained a project for Bower distribution so I don't know what the best answer is (you guys probably have some ideas already) but after doing some research here is what I came up with.

**Tell Bower to ignore everything:** According to [this blog post](http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/) it is pretty common to use the `ignore` property in `bower.json` to ignore everything except what should be distributed. Thoughtbot's Bourbon project [takes this approach](https://github.com/thoughtbot/bourbon/blob/master/bower.json).

**Create a project specifically for Bower distribution:** Having a separate project specifically for Bower distribution also appears to be pretty common. As an example this is [what the Angular team does](https://github.com/angular/bower-angular-resource).

Thoughts?

**Comment by epeli** [comment]
I think we can just drop the ignore on `/dist` because it's not actually working as I thought it would. I thought it would hide changes to the dist files from `git status` but it does not.

**Comment by stoeffel** [comment]
> I think we can just drop the ignore on /dist

:+1:

**Comment by caspyin** [comment]
That's interesting. To me it makes sense that you would want to ignore the `/dist` directory as a maintainer so I didn't really think that would be an option.

But since you specify the `./dist/underscore.string.js` in the `main` property of `bower.json` it makes sense to me now that you'll need to **not** ignore it.

Thanks.

**Comment by stoeffel** [comment]
If we drop the dist from .gitignore we'll have to make sure that the gh-pages download links point to the tag of the current release and not to master.

**Comment by epeli** [comment]
@stoeffel I don't think nothing changes from this. We'll still just commit files on `dist` only when doing releases.

**Comment by stoeffel** [comment]
@epeli yes you are right. And we can reject PRs with dist files.

**Comment by epeli** [comment]
@caspyin try 3.0.2 to see if this issue is fixed now

**Comment by caspyin** [comment]
Yep it does! Thanks, you're both awesome! :beers:
