### ISSUE TITLE
Request for v2.0.0 tag correction

### ISSUE THREAD

**Issue by tomasAlabes** [epeli/underscore.string#430]
Hi, I need to use the version `2.0.0` with Bower and as the tag says `v.2.0.0` instead of `v2.0.0` I can't use it. If I try referencing to the commit bower also complains that the tag is malformed.
Was this on purpose? Because I found others with the same problem: `v.2.2.0rc` and `v.2.1.1`.
Do you have any workaround if it was?

Thanks!

**Comment by stoeffel** [comment]
`bower install 'underscore.string#v.2.0.0'` works for me...
![screen shot 2015-06-08 at 21 46 20](https://cloud.githubusercontent.com/assets/1217681/8043680/f54b50ac-0e27-11e5-9c29-05a1bda1168c.png)

**Comment by tomasAlabes** [comment]
The ' ' did worked in the command line, but how would you do it in the bower.json?
```
"underscore.string": "2.0.0",
"underscore.string": "v.2.0.0",
"underscore.string": ".2.0.0",
"underscore.string": "#f7ad9b6"
"underscore.string": "epeli/underscore.string.git#f7ad9b6"
```
Thanks

**Comment by stoeffel** [comment]
I will try tomorrow in bower.json

**Comment by stoeffel** [comment]
Did you try:
```
"underscore.string": "underscore.string.git#v.2.0.0"
```
?

**Comment by tomasAlabes** [comment]
"underscore.string": "http://github.com/epeli/underscore.string.git#v.2.0.0" works...

Is there any reason to do this? I'm just curious.

**Comment by stoeffel** [comment]
> Is there any reason to do the v.2.0.0 thing? 

no. there is no reason and we don't do that anymore :smiley:

**Comment by tomasAlabes** [comment]
So can it be changed to use the normal v2.0.0 style? So it can be used as any other normal version and people don't need to use the whole url and tag in the bower.json... :)

**Comment by stoeffel** [comment]
hmm. I don't think that it's a good idea to change the tag name since people may already depend on that. maybe you could move to a newer version instead? 2.4.0 is the last before 3.0.0 if you don't want to upgrade to 3.0

**Comment by tomasAlabes** [comment]
I wish I could but I can't... but I understand your concern.
Thanks anyway :)
