### ISSUE TITLE
ReplaceAll - Bug when replacing with same value

### ISSUE THREAD

**Issue by Fizzleban** [epeli/underscore.string#438]
If I do the following:

var a= _s.replaceAll("1234.00", ",", ",")

Variable a will be "......." instead of "1234.00".

**Comment by stoeffel** [comment]
Hmm... did just try it. It works for me. Could you add a jsfiddle with a case where this doesn't work?

**Comment by stoeffel** [comment]
:bell: did you try it again? which version are you using?

**Comment by stoeffel** [comment]
I guess this is resolved know.
