### ISSUE TITLE
slugify with all caps does not work as expected

### ISSUE THREAD

**Issue by paulovieira** [epeli/underscore.string#464]
I'm not sure if this is an issue or not, but I was surprised with the following behaviour:

`s.slugify("ABC XYZ")`returns `"a-b-c-x-y-z"`. I think the expected value would be `"abc-xyz"`

**Comment by dperrymorrow** [comment]
i have experienced this as well in the past with capitalization. 
Is this considered a bug? if so i can attempt to do a pull

**Comment by epeli** [comment]
Yes this is a bug but I have a feeling we've fixed this already once :) PR welcome if it happens on the master too.

**Comment by paulovieira** [comment]
Yes, I confirm that it is fixed in master (fixed with #448).
