### ISSUE TITLE
Fix weird scrolling on the docs page

### ISSUE THREAD

**Issue by mrchief** [epeli/underscore.string#465]
http://epeli.github.io/underscore.string/ on Chrome (might happen on other browsers as well) suffers from weird scrolling issue. 

Steps to repro:

 - Navigate to page
 - Click on `API` first, then `Usage` at the top menu
 - Use Chrome's search function and search for any string (e.g. "format")
 - The 5th match is for `sprintf` function which also happens to be somewhat down in the page
 - Move your mouse and try clicking the "original page" link

The page scrolls to top. 

This is just an example and in general,once you click on usage, moving your mouse on the page anywhere scrolls the page to some place. 

![underscore string scroll issue](https://cloud.githubusercontent.com/assets/781818/11483829/afa203d6-9778-11e5-9b96-8197607615e2.gif)

**Comment by stoeffel** [comment]
Hmm... This doesn't happen in my chrome (v47)

**Comment by mrchief** [comment]
Doesn't happen on Chrome v48.0.2564.71 beta-m either. I'll check on the other desktop where it was happening (was Chrome Canary at the time of reporting). Maybe its no longer a issue.

**Comment by mrchief** [comment]
Does happen on Chrome Version 47.0.2504.0 canary (64-bit)

**Comment by mrchief** [comment]
Does not happen on Chrome Version 49.0.2621.0 canary (64-bit). I guess its not really your issue then. Closing.

**Comment by stoeffel** [comment]
Thanks for checking it again.
