### ISSUE TITLE
Can you create a release?

### ISSUE THREAD

**Issue by ekawas-de** [epeli/underscore.string#468]
We are using a library that depends on your module. They are  using the latest version of your library but there is a memory leak in it. You have already fixed the leak and so would it be possible for you to create a release so that our dependency utilizes your fix?

**Comment by AdrieanKhisbe** [comment]
:+1:

**Comment by ekawas-de** [comment]
Any word?

**Comment by stoeffel** [comment]
I will have time to publish 3.3.0 on Friday (maybe @epeli is faster :smile:). But I didn't see where we fixed a memory leak. Can you point me to the commit? [This](https://github.com/epeli/underscore.string/compare/3.2.2...master) are all the commits since 3.2.2.

**Comment by epeli** [comment]
I'll try to do it earlier. Our release process is a bit involved...

**Comment by stoeffel** [comment]
Cool. Less work for me :sweat_smile:

**Comment by ekawas-de** [comment]
Sorry, not a memory leak but a global variable leak. https://github.com/epeli/underscore.string/commit/bb4f12bd2039414de50e2302cdf67fa51c000ecb

**Comment by stoeffel** [comment]
:smile: oki. Thought I missed something.

**Comment by ekawas-de** [comment]
Thank you guys very much!

**Comment by epeli** [comment]
Finally managed to do this. Sorry for taking so long!

**Comment by ekawas-de** [comment]
Thanks again!

**Comment by AdrieanKhisbe** [comment]
GREAT! Thanks !!
