### ISSUE TITLE
Use npmcdn.com instead of commiting build artifacts into git

### ISSUE THREAD

**Issue by epeli** [epeli/underscore.string#478]
Keeping build artifacts in git is bad for so many reasons...

To do this we can just remove the `dist` from git and create it on npm prepublish hook.

Old school users can then just download the bundle from 

https://npmcdn.com/underscore.string@3.2.2/dist/underscore.string.min.js

or even stick it to script tag directly.

**Comment by stoeffel** [comment]
SGTM
