### ISSUE TITLE
High severity vulnerability found on underscore.string@3.3.4

### ISSUE THREAD

**Issue by jpw** [epeli/underscore.string#515]
Regular Expression Denial of Service (ReDoS)
https://snyk.io/vuln/npm:underscore.string:20170908
Thanks for having a look.

**Comment by emersoncloud** [comment]
+1 
@jpw Do you have any updates on this?

**Comment by wboyle-erwin** [comment]
@epeli Is there any way we can get a update to fix this issue?

**Comment by epeli** [comment]
It talks about date parsing but this library has no date parsing functions. What's the affected part?

**Comment by epeli** [comment]
Is #510 related?

**Comment by jpw** [comment]
Yep, I now see this is a duplicate of https://github.com/epeli/underscore.string/issues/510
Sorry for the noise, will close this issue!
